//! Appends a translated clone of one supported vector stroke.

use std::{env, fs::File};

use clipfile::{ClipFile, Limits};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Select one VectorObjectList row, stroke, and integer translation.
    let args = env::args().collect::<Vec<_>>();
    if args.len() != 8 {
        return Err(
            "usage: cargo run --features write --example clone_vector_stroke -- \
             <input.clip> <new-output.clip> <layer-id> <vector-row-id> \
             <stroke-index> <dx> <dy>"
                .into(),
        );
    }
    let layer_id = args[3].parse::<i64>()?;
    let row_id = args[4].parse::<i64>()?;
    let stroke_index = args[5].parse::<usize>()?;
    let delta_x = args[6].parse::<i32>()?;
    let delta_y = args[7].parse::<i32>()?;
    let limits = Limits::default();

    // Resolve a typed source before opening the conservative writer.
    let mut clip = ClipFile::open(File::open(&args[1])?)?;
    let database = clip.open_database()?;
    let source = database
        .vector_data_sources(layer_id, limits)?
        .into_iter()
        .find(|source| source.id() == row_id)
        .ok_or("the requested vector row does not belong to this layer")?;

    // Preserve the full stroke record and translate only coordinates/bounds.
    let mut writer = clip.writer()?;
    let (new_index, summary) =
        writer.clone_vector_stroke(&source, stroke_index, delta_x, delta_y, limits)?;

    // Saved raster caches are deliberately not regenerated by this operation.
    writer.write_to_path(&args[2])?;
    println!(
        "appended stroke {new_index}: {} point(s), delta=({}, {})",
        summary.points(),
        summary.delta_x(),
        summary.delta_y()
    );
    Ok(())
}
